from django.urls import path
from . import views

urlpatterns = [
    path("register/", views.register, name='register'),
    path("", views.login_view, name='login'),
    path("logout/", views.logout_view, name='logout'),
    path("home/", views.home, name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
    path('create-category/', views.create_category, name='create_category'),
    path('product_list/', views.product_list, name='product_list'),
    path('create_product/', views.create_product, name='create_product'),
    path('add-cart/<int:product_id>/',views.add_cart, name='add_cart'),
    path('cart/',views.cart_view,name='cart_view'),
    path('remove-from-cart/<int:cart_id>/', views.remove_cart, name='remove_cart'),
    path('category_list/',views.Category_list, name='category_list'),
    path('update-products/<int:id>/',views.update_product, name='update_product'),
    path('delete-product/<int:id>/', views.delete_product, name='delete_product'),
    path('cart/increment/<int:cart_id>/',views.increment_quantity, name='increment_quantity'),
    path('cart/decrement/<int:cart_id>/',views.decrement_quantity, name='decrement_quantity'),
    path('cart/remove_all_cart/',views.remove_all_cart, name='remove_all_cart'),
    path('place_order/', views.place_order, name='place_order'),
    path('payment/<int:order_id>/', views.payment, name='payment'),
    path('success/',views.success, name='success'),
    path('order_history/',views.order_history, name='order_history'),
    path('update_order_status/<int:order_id>/',views.update_order_status, name='update_order_status'),
    path('all_orders/',views.all_orders, name='all_orders'),
]